name: Reusable Deploy
on: workflow_call       #Allows this workflow to be called by other workflows.
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Output info
       run: echo "Deploying and uploading"