name: Reusable Deploy
on: 
 workflow_call:
    inputs:
        artifact-name:
            description: The name of the deployable artifact files.
            required: false
            default: dist 
            type: string #Allows this workflow to be called by other workflows.
#    secrets:   With this 3 lines you would take a secret passed from the use-reuse yml.
#      some-secret:
#        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Get Code
       uses: actions/download-artifact@v4
       with:
        name: ${{ inputs.artifact-name}}
     - name: List files
       run: ls
     - name: Output info
       run: echo "Deploying and uploading"